# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [7]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

height_array = np.array(height)
weight_array = np.array(weight)

BMI = weight_array / (height_array ** 2) * 730
BMI

array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [11]:
import numpy as np

def random_matrix(rows, cols):
    return np.random.randint(0, 10, size=(rows, cols))
rows = 3
cols = 4
random_mat = random_matrix(rows, cols)
print(f"Random {rows}x{cols} Matrix:")
print(random_mat)


Random 3x4 Matrix:
[[2 9 5 1]
 [6 7 9 6]
 [9 4 0 0]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [ ]:
import csv
import numpy as np

In [15]:
# I don't think I fully understood the question here, but I tried.

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# Use this function to actually open the data inside of a NDArray.

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('redsox_2017_hitting.txt')
bs2018 = load_data('redsox_2018_hitting.txt')

SLG_difference = sum(bs2017['SLG']) - sum(bs2018['SLG'])
print('\n Difference in SLG from 2017 to 2018: {}'.format(SLG_difference))


 Difference in SLG from 2017 to 2018: 1.296999879181385
